- metric: matrix_cov_fro
  mode: min
  filename: best-matrix_cov_fro
  save_last: true
- metric: matrix_cov_fro_rel
  mode: min
  filename: best-matrix_cov_fro_rel
  save_last: false
- metric: matrix_cov_mse
  mode: min
  filename: best-matrix_cov_mse
  save_last: false
- metric: matrix_cov_mae
  mode: min
  filename: best-matrix_cov_mae
  save_last: false
- metric: matrix_cov_diag_mape
  mode: min
  filename: best-matrix_cov_diag_mape
  save_last: false
- metric: matrix_corr_fro
  mode: min
  filename: best-matrix_corr_fro
  save_last: false
- metric: matrix_corr_fro_rel
  mode: min
  filename: best-matrix_corr_fro_rel
  save_last: false
- metric: matrix_corr_cross_mse
  mode: min
  filename: best-matrix_corr_cross_mse
  save_last: false
- metric: matrix_corr_offdiag_pearson
  mode: max
  filename: best-matrix_corr_pearson
  save_last: false
- metric: matrix_corr_offdiag_spearman
  mode: max
  filename: best-matrix_corr_spearman
  save_last: false
- metric: matrix_corr_sign_rate
  mode: max
  filename: best-matrix_corr_sign_rate
  save_last: false
- metric: series_rmse
  mode: min
  filename: best-series_rmse
  save_last: false
- metric: series_nd
  mode: min
  filename: best-series_nd
  save_last: false
- metric: series_nrmse
  mode: min
  filename: best-series_nrmse
  save_last: false
- metric: series_nd_sum
  mode: min
  filename: best-series_nd_sum
  save_last: false
- metric: series_nrmse_sum
  mode: min
  filename: best-series_nrmse_sum
  save_last: false
- metric: series_crps
  mode: min
  filename: best-series_crps
  save_last: false
- metric: series_crps_sum
  mode: min
  filename: best-series_crps_sum
  save_last: false
- metric: corr_wasserstein_flat
  mode: min
  filename: best-corr_wasserstein
  save_last: false
- metric: corr_diag_abs_mean
  mode: min
  filename: best-corr_diag_mean
  save_last: false
- metric: corr_diag_abs_std
  mode: min
  filename: best-corr_diag_std
  save_last: false
- metric: corr_symmetry_abs_mean
  mode: min
  filename: best-corr_symmetry_mean
  save_last: false
- metric: corr_symmetry_abs_std
  mode: min
  filename: best-corr_symmetry_std
  save_last: false
- metric: corr_mean_correl_abs_diff
  mode: min
  filename: best-corr_mean_correl
  save_last: false
- metric: corr_eigen_gini_abs_diff
  mode: min
  filename: best-corr_eigen_gini
  save_last: false
- metric: corr_coph_single_abs_diff
  mode: min
  filename: best-corr_coph_single
  save_last: false
- metric: corr_coph_ward_abs_diff
  mode: min
  filename: best-corr_coph_ward
  save_last: false
- metric: corr_perron_frob_abs_diff
  mode: min
  filename: best-corr_perron
  save_last: false
- metric: corr_power_eigen_abs_diff
  mode: min
  filename: best-corr_power_eigen
  save_last: false
- metric: spectral_power_abs_error
  mode: min
  filename: best-spectral_power_abs_error
  save_last: false
- metric: fourier_time_sliced_wasserstein_mean
  mode: min
  filename: best-fourier_time_sw_mean
  save_last: false
- metric: fourier_time_marginal_wasserstein_mean
  mode: min
  filename: best-fourier_time_mw_mean
  save_last: false
- metric: fourier_freq_sliced_wasserstein_mean
  mode: min
  filename: best-fourier_freq_sw_mean
  save_last: false
- metric: fourier_freq_marginal_wasserstein_mean
  mode: min
  filename: best-fourier_freq_mw_mean
  save_last: false
- metric: fourier_spectral_marginal_wasserstein_mean
  mode: min
  filename: best-fourier_spectral_mw_mean
  save_last: false
